services:
  # APIサーバー
  api:
    build: .
    ports:
      - "8081:8081"
    env_file: .env
    depends_on:
      - db

  # PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sana
      POSTGRES_PASSWORD: zenpassword
      POSTGRES_DB: auto_zen_db
    ports:
      - "5432:5432"
  volumes:
    - ./postgres_data:/var/lib/postgresql/data